### ISSUE TITLE
Check that the int type is acceptable

### ISSUE THREAD

**Issue by rickardnorlander** [danieleades/arithmetic-coding#33]
The Model has a B parameter, which is the int type used for internal calculations. I tried using a 2^32 denominator with B=u64, and this lead to the program hanging, and not knowing the exact details of arithmetic coding works, it took me some time to figure out what the issue was. It would be good if there was some check that the max_denominator is compatible with the int size.

**Comment by danieleades** [comment]
the check you're describing can be found here - https://github.com/danieleades/arithmetic-coding/blob/38380db210c46b33f7026fd9f285fa567f73c31e/src/encoder.rs#L71

note that these checks only run on debug builds.

are you able to provide a reproduction of the issue I can take a look at?

**Comment by danieleades** [comment]
there's also a second debug check here - https://github.com/danieleades/arithmetic-coding/blob/38380db210c46b33f7026fd9f285fa567f73c31e/src/encoder.rs#L142

this one checks that your model is honouring the `max_denominator` parameter

**Comment by rickardnorlander** [comment]
Oh yeah I was running in release mode, doh!
